#!/usr/bin/env bash
# =====================================================================
# AAA :: provision an Azure Database for PostgreSQL (Flexible Server)
# for the AAA web app, and write .env.production for deploy/deploy.sh.
# ---------------------------------------------------------------------
# Run after `az login`. Creates the server (Burstable B1ms, PG16),
# allow-lists pgcrypto+citext, opens the firewall to this machine's IP
# and to Azure services (so the Container App can connect), creates the
# `aaa` database, generates strong passwords, and writes .env.production.
# Then run:  ./deploy/deploy.sh production   (applies schema + roles)
# Safe to re-run: if the server exists, the admin password is reset.
# =====================================================================
set -uo pipefail

# ── settings ─────────────────────────────────────────────────────────
RG=aaa-rg
LOC=westus2                 # co-located with the Container App + shared ACR
SERVER=aaa-postgres
DB=aaa
ADMIN_USER=aaadmin
TIER=Burstable
SKU=Standard_B1ms
STORAGE=32
PGVER=16
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# ─────────────────────────────────────────────────────────────────────

command -v az >/dev/null || { echo "ERROR: az not found"; exit 1; }
az account show >/dev/null 2>&1 || { echo "ERROR: run az login"; exit 1; }

MYIP="$(curl -s --max-time 10 https://api.ipify.org 2>/dev/null || curl -s --max-time 10 https://ifconfig.me 2>/dev/null)"
[ -n "$MYIP" ] || { echo "ERROR: could not detect public IP"; exit 1; }
echo "==> deploy machine IP: $MYIP"

# URL-safe, complexity-satisfying passwords (hex + Aa7 => lower+digit+upper)
ADMIN_PW="$(openssl rand -hex 18)Aa7"
RW_PW="$(openssl rand -hex 18)Aa7"
RO_PW="$(openssl rand -hex 18)Aa7"

if az postgres flexible-server show -g "$RG" -n "$SERVER" >/dev/null 2>&1; then
  echo "==> server $SERVER exists — resetting admin password"
  az postgres flexible-server update -g "$RG" -n "$SERVER" --admin-password "$ADMIN_PW" -o none
else
  echo "==> creating server $SERVER ($SKU, PG$PGVER, $LOC) — ~3-5 min"
  az postgres flexible-server create -g "$RG" -n "$SERVER" -l "$LOC" \
    --version "$PGVER" --tier "$TIER" --sku-name "$SKU" --storage-size "$STORAGE" \
    --admin-user "$ADMIN_USER" --admin-password "$ADMIN_PW" \
    --public-access "$MYIP" --yes -o none \
    || { echo "  FAIL server create"; exit 2; }
  echo "  new  server $SERVER"
fi

echo "==> firewall: allow this machine + Azure services (for the Container App)"
az postgres flexible-server firewall-rule create -g "$RG" -n "$SERVER" \
  --rule-name deploy-machine --start-ip-address "$MYIP" --end-ip-address "$MYIP" -o none 2>/dev/null
az postgres flexible-server firewall-rule create -g "$RG" -n "$SERVER" \
  --rule-name AllowAzureServices --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0 -o none 2>/dev/null

echo "==> allow-listing extensions pgcrypto + citext"
az postgres flexible-server parameter set -g "$RG" -s "$SERVER" \
  --name azure.extensions --value PGCRYPTO,CITEXT -o none

echo "==> ensuring database '$DB' exists"
az postgres flexible-server db create -g "$RG" -s "$SERVER" -d "$DB" -o none 2>/dev/null \
  && echo "  ok   database $DB created" || echo "  ok   database $DB (already exists)"

HOST="$(az postgres flexible-server show -g "$RG" -n "$SERVER" --query fullyQualifiedDomainName -o tsv)"

echo "==> writing $ROOT/.env.production (gitignored)"
cat > "$ROOT/.env.production" <<EOF
# Generated by deploy/azure-postgres.sh — gitignored. Real credentials.
DEPLOY_ENV=production
PGHOST=$HOST
PGPORT=5432
PGDATABASE=$DB
PGADMIN_USER=$ADMIN_USER
PGADMIN_PASSWORD=$ADMIN_PW
PGSSLMODE=require
APP_RW_PASSWORD=$RW_PW
APP_RO_PASSWORD=$RO_PW
APP_DATABASE_URL=postgresql://app_rw:$RW_PW@$HOST:5432/$DB?sslmode=require
EOF
chmod 600 "$ROOT/.env.production"

cat <<EOF

==> DONE. Server: $HOST  (db=$DB, admin=$ADMIN_USER)
    Next:
      ./deploy/deploy.sh production      # applies migrations + seeds + app_rw/app_ro roles
    Then set the app's DATABASE_URL to the app_rw connection string in .env.production
    (APP_DATABASE_URL). Passwords are saved in .env.production only.
EOF
